version: "3.0"
services:
  master:
    container_name: master
    build: ./master


  client-1:
    container_name: client-1
    build: ./client
    depends_on:
      - master
    tty: true
  client-2:
    container_name: client-2
    build: ./client
    depends_on:
      - master
    tty: true


  edge-node-1:
    container_name: edge-node-1
    build: ./server
    depends_on:
      - master
  edge-node-2:
    container_name: edge-node-2
    build: ./server
    depends_on:
      - master
  edge-node-3:
    container_name: edge-node-3
    build: ./server
    depends_on:
      - master
