version: "3.0"
services:
  master:
    container_name: master
    build: ./master


#  production-site-1:
 #   container_name: production-site-1
  #  build: ./production-site
  #  depends_on:
  #    - master
#  production-site-2:
#    container_name: production-site-2
#    build: ./production-site
#    depends_on:
#      - master

  client-cli:
    container_name: client-cli
    build: ./client-cli
    depends_on:
      - master
    tty: true
    stdin_open: true

  edge-node-1:
    container_name: edge-node-1
    build: ./server
    stop_signal: SIGINT
    depends_on:
      - master
    volumes:
      # Mount /var/run so we can access docker.sock and talk to Docker
      - /var/run:/var/run
      # Mount the shared configuration directory, used by the AWS SDKs
      - $HOME/.aws/:/home/.aws/
      # Named volume
      - backup1:/app/vol
    environment:
      # define the home folder; credentials will be read from $HOME/.aws
      HOME: "/home"
      # You can change which AWS CLI Profile is used
      AWS_PROFILE: "default"
      AWS_DEFAULT_REGION: "us-east-1"
  edge-node-2:
    container_name: edge-node-2
    build: ./server
    stop_signal: SIGINT
    depends_on:
      - master
    volumes:
      # Mount /var/run so we can access docker.sock and talk to Docker
      - /var/run:/var/run
      - $HOME/.aws/:/home/.aws/
      - backup2:/app/vol
    environment:
      HOME: "/home"
      AWS_PROFILE: "default"
      AWS_DEFAULT_REGION: "us-east-1"
  edge-node-3:
    container_name: edge-node-3
    build: ./server
    stop_signal: SIGINT
    depends_on:
      - master
    volumes:
      # Mount /var/run so we can access docker.sock and talk to Docker
      - /var/run:/var/run
      - $HOME/.aws/:/home/.aws/
      - backup3:/app/vol
    environment:
      HOME: "/home"
      AWS_PROFILE: "default"
      AWS_DEFAULT_REGION: "us-east-1"
  edge-node-4:
    container_name: edge-node-4
    build: ./server
    stop_signal: SIGINT
    depends_on:
      - master
    volumes:
      # Mount /var/run so we can access docker.sock and talk to Docker
      - /var/run:/var/run
      - $HOME/.aws/:/home/.aws/
      - backup4:/app/vol
    environment:
      HOME: "/home"
      AWS_PROFILE: "default"
      AWS_DEFAULT_REGION: "us-east-1"


volumes:
  backup1:
  backup2:
  backup3:
  backup4:

